#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=dl1_lstm
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=3:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05
source activate dl1_gpu
export PYTHONIOENCODING=utf8

cd $HOME/dl1-labs/assignment2/part2/
srun python -u train.py --txt_file assets/book_EN_democracy_in_the_US.txt
