#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=dl_part1_all
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05
source activate dl1_gpu

cd $HOME/dl1-labs/assignment2/part1/
rsync -a $HOME/dl1-labs/assignment2/part1/data/ $TMPDIR
srun python -u main_cnn.py --data_dir "/scratch/"
